use_frameworks!

platform :ios, '9.0'

target 'EasyDateFormatter_Example' do
  pod 'EasyDateFormatter', :path => '../', :testspecs => ['Tests']

  target 'EasyDateFormatter_Tests' do
    inherit! :search_paths

    
  end
end
