# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode13.3
language: swift
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/EasyDateFormatter.xcworkspace -scheme EasyDateFormatter-Example -sdk iphonesimulator -destination "generic/platform=iOS Simulator,OS=13.0,name=iPhone X" ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
