language:
  - swift
osx_image: xcode13.3
before_install:
  - gem install cocoapods
  - pod install --project-directory=Example
script:
  - xcodebuild -workspace Example/EasyDateFormatter.xcworkspace -scheme EasyDateFormatter-Example -sdk iphonesimulator15.4 -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.4' build test
  - pod lib lint