language:
  - swift
osx_image: xcode13.3
script:
  - xcodebuild -workspace Example/EasyDateFormatter.xcworkspace -scheme EasyDateFormatter-Example -sdk iphonesimulator15.4 -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.4' build test
  - pod lib lint
after_success:
  - bash <(curl -s https://codecov.io/bash)
